### PR TITLE
Fix appearence

### PR DESCRIPTION
**Pull request by GGBBB2000**

### CODE REVIEW

**Comment by equal-l2** [comment]
You should put your commit to the branch other than master when you make a pull request.

Suppose the owner merge your commit into his master, your master will conflict with owner's.

**Comment by equal-l2** [comment]
This page will help you to solve the problem.
https://qiita.com/atskimura/items/a90dfa8bfc72e3657ef9 (Japanese)

**Comment by GGBBB2000** [comment]
You mean that I should switch the branch which do "git push", don't you?

**Comment by equal-l2** [comment]
Have you make a commit on the other branch?
If so, you're right, just push to the branch other than `master`.

**Pull request closed without merging**
